---
name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: cliffano/command-docker-action@v1.1.0
      with:
        image: cliffano/studio:2.0.1
        command: 'make ci'
