---
name: Generate Vars File
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          set-safe-directory: ${{ github.workspace }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: git config --global user.email 'pakkunbot'
      - run: git config --global user.name 'blah+pakkun@cliffano.com'
      - run: make clean deps x-gen-vars-file
      - run: git commit -am 'Generate vars file with latest Minecraft versions'
      - uses: ad-m/github-push-action@v0.8.0
        with:
          tags: false
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
